### ISSUE TITLE
Plugin SDK broken: Horos never issues OsirixViewerControllerDidLoadImagesNotification

### ISSUE THREAD

**Issue by aglv** [horosproject/horos#57] opened 2016-02-03 08:12 UTC
Commit 0a285386285e532b8cf992060511c52d5d327c8c causes OsiriX to never issue OsirixViewerControllerDidLoadImagesNotification, with heavy consequences on parts of OsiriX that rely on that notification. My commit 81d2868 (in aglv/Horos, in pull request #49) fixes this, but there are probably consequences on the intended performance enhancement.

**Comment by fvpolpeta** [comment] 2016-02-03 12:52
Thanks AGLV. We will review that. The 0a28538 was intended to speed up the process of aborting the loading the images. Therefore, OsirixViewerControllerDidLoadImagesNotification should not be issued when aborting image loading. But, based on your comment I review if there is any collateral effect in the direction of not issuing the referred notification even when the loading process is not aborted.

**Comment by fvpolpeta** [comment] 2016-02-03 12:58
Got it. Can you test for me:

I believe that in finishLoadImageData the correct statement is:

if (requestLoadingCancel)
      return;

At this point the thread is possibly no longer being executed, but if user requested cancel that will be detected by "requestLoadingCancel".

Best

**Comment by aglv** [comment] 2016-02-03 16:11
Tested, works for me,
is in my commit 5ca7e1d, part of merge request #49 
Thanks!

**Comment by fvpolpeta** [comment] 2016-02-03 19:58
Thanks. I made some other changes, which were committed in 2a5a8e9.
requestLoadingCancel variable was wrongly used in some places.

**Closed as completed** 2016-02-03 20:00 UTC
