### ISSUE TITLE
wrong colour displayed in Horos

### ISSUE THREAD

**Issue by Paskob** [horosproject/horos#88] opened 2016-05-10 01:38 UTC
Hi there. I can't figure out this strange bug. Images pulled from PACS do not display the correct colours. Yet the same DICOM files opens with alternative apps are fine including Osirix and Osirix-LXIV. Here is some same data to test. 
[Anonymized - 47850.1P.zip](https://github.com/horosproject/horos/files/256220/Anonymized.-.47850.1P.zip)

**Comment by fvpolpeta** [comment] 2016-05-14 14:56
Hi,

This is not a bug in principle. See my attached image and try to adequate your Viewer settings as mine are.

For safety, restart Horos after having configured it.

![screen shot 2016-05-14 at 11 54 03 am](https://cloud.githubusercontent.com/assets/7875949/15269089/b7beee60-19ca-11e6-99a6-3d31e03844a6.png)

Please, let me know your results.

BR

**Comment by Paskob** [comment] 2016-05-14 21:08
Hi there, 

Thank you for your reply. I have applied the same settings but unfortunately I’m still getting the strange colours. There must be some other obscure setting I must have wrong?

Regards
P

**Comment by fvpolpeta** [comment] 2016-05-15 15:45
Please, try this nightly build of version 2.0.0 of Horos:

https://dl.dropboxusercontent.com/u/15111870/PurView/Horos%202016-05-15%2012-42-13.zip

=> El Capitan is required
=> Plugins not activated

If the problem persists I will work on providing you with my whole settings setup.

BR

**Comment by Paskob** [comment] 2016-05-15 22:07
Thank you for the nightly build. 
Unfortunately its still the same…

**Comment by fvpolpeta** [comment] 2016-05-16 01:08
That is very intriguing. Your images work properly in my system as you can note in the screenshot above.

In attachment, some other configurations of mine.

Hope it helps
[Archive.zip](https://github.com/horosproject/horos/files/265397/Archive.zip)

**Comment by Paskob** [comment] 2016-05-16 01:15
That worked! There was a couple other things different on the other settings page you sent me. 

Thank you so much! Much appreciated

**Comment by fvpolpeta** [comment] 2016-05-16 01:16
You are welcome. Closing the issue.

Best

**Closed as completed by fvpolpeta** 2016-05-16 01:16 UTC
