### ISSUE TITLE
Horos Quit Unexpectedly

### ISSUE THREAD

**Issue by justinroberts22** [horosproject/horos#47] opened 2015-12-30 17:28 UTC
I have been trying to open to my Horos viewer but keep getting the following error message (see attached).  I tried upgraded to the latest version (1.1.4) and the problem persists.  
![screen shot 2015-12-30 at 9 26 06 am](https://cloud.githubusercontent.com/assets/16482022/12054337/aab45df8-aed7-11e5-949e-5152f34cbb4a.png)

**Comment by fvpolpeta** [comment] 2015-12-30 17:44
Hi,

Please, check if the following nightly build solves your problem. If nit, send us the images series that caused the crash after anonymizing the patient data.

https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightly.app.zip

BR

https://dl.dropboxusercontent.com/u/15111870/PurView/HorosNightly.app.zip

**Comment by justinroberts22** [comment] 2015-12-30 18:58
Unfortunately, that nightly build did not fix the problem.  Also, I am
unable to anonymize the study because I cannot access Horos at all.  I was
going to have another colleague anonymize the study in his Horos but the
same study crashed his viewer as well.

Justin Roberts, R.T. (MR)

Applications Specialist
CorTechs Labs, Inc - www.cortechslabs.com
4690 Executive Dr., Suite 250, San Diego, CA  92121
Tel +1 858 459 9700 x 511 <%2B1%20858%20459%209700%20x%20517>

Meet us in Chicago at RSNA 2015
http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg1qwvwHW1q0FWz7fsWKFW643SkR56dK6pf2MB4hz02?t=http%3A%2F%2Fwww.rsna.org%2FAnnual_Meeting.aspx&si=6433241223659520&pi=d1b37224-40b9-4dc9-e565-ad996b631228
!

Booth #1861, Hall A: South

CorTechs On the Brain
http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg1qwvwHW1q0FWz7fsWKFW643SkR56dK6pf2MB4hz02?t=http%3A%2F%2Fcortechsnews.cortechslabs.com%2F&si=6433241223659520&pi=d1b37224-40b9-4dc9-e565-ad996b631228
–
Read our blog to discover more about NeuroQuant and CorTechs Labs
Learn more about NeuroQuant 2.0. Watch our latest video
http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg1qwvwHW1q0FWz7fsWKFW643SkR56dK6pf2MB4hz02?t=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DHbYWz6dUnF8&si=6433241223659520&pi=d1b37224-40b9-4dc9-e565-ad996b631228
.

Confidentiality Note: The information in this e-mail is intended only for
the person to whom it is addressed and may contain information that is
privileged, confidential, and exempt from disclosure under applicable law.
If you believe this e-mail was sent to you in error, please contact the
sender by return e-mail and destroy all copies of the original message. If
you are not the intended recipient, you are hereby notified that any use,
forwarding, dissemination, or reproduction of this message is strictly
prohibited and may be unlawful.

**Comment by fvpolpeta** [comment] 2016-01-02 17:33
Justin;

I'm almost sure the problem is being caused because the first study in your database is being mishandled by Horos.

I suggest you to start Horos in Safe Mode (Shift + Option + Click for launching) and then send me an anonymized version of these images. Also export as your own backup the study and then remove it study from your database in order to have Horos properly starting.

With your anonymized images, when I find out what is causing the crash, we will implement a fix and generate a Nightly Build tol enable you to import such study from the backup you have made.

BR and Happy 2016

**Comment by justinroberts22** [comment] 2016-01-04 17:47
Fauze,

Thank you so much for your time on this.  You're right, I think there is
something wrong with the study I was trying to import.  I had a work
colleague import the same study into his Horos viewer and we received the
same error message.  The same study also created problems for one of our
K-Pacs viewers.  We were able to resolve the issue by renaming the original
"Horos Data" folder to something different and then deleting the study from
that database.  Luckily I was able to retain all my data when renaming the
folder back to "Horos Data".

Thanks for all your help on this.  I really appreciate it.
-Justin

Justin Roberts, R.T. (MR)

Applications Specialist
CorTechs Labs, Inc - www.cortechslabs.com
4690 Executive Dr., Suite 250, San Diego, CA  92121
Tel +1 858 459 9700 x 511 <%2B1%20858%20459%209700%20x%20517>

CorTechs On the Brain
http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg1qwvwHW1q0FWz7fsWKFW643SkR56dK6pf2MB4hz02?t=http%3A%2F%2Fcortechsnews.cortechslabs.com%2F&si=6433241223659520&pi=6e63a7ad-4b4c-409f-ccaf-875ac1ac2462
–
Read our blog to discover more about NeuroQuant and CorTechs Labs
Learn more about NeuroQuant 2.0. Watch our latest video
http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg1qwvwHW1q0FWz7fsWKFW643SkR56dK6pf2MB4hz02?t=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DHbYWz6dUnF8&si=6433241223659520&pi=6e63a7ad-4b4c-409f-ccaf-875ac1ac2462
.

Confidentiality Note: The information in this e-mail is intended only for
the person to whom it is addressed and may contain information that is
privileged, confidential, and exempt from disclosure under applicable law.
If you believe this e-mail was sent to you in error, please contact the
sender by return e-mail and destroy all copies of the original message. If
you are not the intended recipient, you are hereby notified that any use,
forwarding, dissemination, or reproduction of this message is strictly
prohibited and may be unlawful.

**Comment by fvpolpeta** [comment] 2016-01-04 21:51
Thanks for the feedback. I'm closing the issue therefore.

BR

**Closed as completed by fvpolpeta** 2016-01-04 21:51 UTC

**Comment by justinroberts22** [comment] 2016-01-04 22:23
Thanks again,
-Justin

Justin Roberts, R.T. (MR)

Applications Specialist
CorTechs Labs, Inc - www.cortechslabs.com
4690 Executive Dr., Suite 250, San Diego, CA  92121
Tel +1 858 459 9700 x 511 <%2B1%20858%20459%209700%20x%20517>

CorTechs On the Brain
http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg1qwvwHW1q0FWz7fsWKFW643SkR56dK6pf2MB4hz02?t=http%3A%2F%2Fcortechsnews.cortechslabs.com%2F&si=6433241223659520&pi=1c8e3a48-fb87-46d8-e298-995a8662d88d
–
Read our blog to discover more about NeuroQuant and CorTechs Labs
Learn more about NeuroQuant 2.0. Watch our latest video
http://t.sidekickopen35.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg1qwvwHW1q0FWz7fsWKFW643SkR56dK6pf2MB4hz02?t=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DHbYWz6dUnF8&si=6433241223659520&pi=1c8e3a48-fb87-46d8-e298-995a8662d88d
.

Confidentiality Note: The information in this e-mail is intended only for
the person to whom it is addressed and may contain information that is
privileged, confidential, and exempt from disclosure under applicable law.
If you believe this e-mail was sent to you in error, please contact the
sender by return e-mail and destroy all copies of the original message. If
you are not the intended recipient, you are hereby notified that any use,
forwarding, dissemination, or reproduction of this message is strictly
prohibited and may be unlawful.
