### ISSUE TITLE
Report DICOM PDF

### ISSUE THREAD

**Issue by alealla** [horosproject/horos#416] opened 2018-10-23 00:09 UTC
Dicom PDF conversion stopped working on new version.

**Comment by fvpolpeta** [comment] 2018-10-23 01:41
Hi -

Please, can you detail the procedure you execute to the moment you get this failure?

Thanks

Fauze

**Comment by alealla** [comment] 2018-10-23 09:48
I use Horos with this property activated.
<img width="536" alt="captura de tela 2018-10-23 06 40 43" src="https://user-images.githubusercontent.com/23710457/47351637-c692a700-d68e-11e8-8b00-cfa61cc0b0b2.png">

When I finish the report, I change the status of the study to validated.
<img width="105" alt="captura de tela 2018-10-23 06 41 02" src="https://user-images.githubusercontent.com/23710457/47351767-15404100-d68f-11e8-92ff-13a94646cfdd.png">

So it creates a Dicom encapsulated PDF report as a new serie of the study.
<img width="244" alt="captura de tela 2018-10-23 06 41 47" src="https://user-images.githubusercontent.com/23710457/47351854-3b65e100-d68f-11e8-85fc-bcc93ccf644b.png">

But it is not working anymore on Horos 3.3.

**Comment by fvpolpeta** [comment] 2018-10-23 09:54
Thanks. We will check.

Fauze

**Comment by alealla** [comment] 2018-10-23 09:57
Thank you.

**Comment by mrbroome** [comment] 2018-10-23 18:20
I can confirm that this feature no longer works for me either as an automatic conversion (I use the same method as alealla) or via the manual method accessed from the 
File > Report > Convert to DICOM PDF
method. This persists on 3.3.1 as well.

**Comment by fvpolpeta** [comment] 2018-10-24 01:17
Thanks. We will be investigating and managing to have it fixed.

Fauze

**Comment by fvpolpeta** [comment] 2018-10-28 12:36
Hi -

Please, try out the build below and let us know if the problem you reported is solved.

This is related to new security requirements in Mojave.

https://horosproject.org/horos-content/Horos3.3.2_Nightly20181028.dmg

Thanks

Fauze

**Comment by alealla** [comment] 2018-10-28 13:08
It worked. Thank you.

**Closed as completed** 2018-11-05 18:16 UTC
