### ISSUE TITLE
No Updates checks: "no internet connection??"

### ISSUE THREAD

**Issue by jacopHoros** [horosproject/horos#281] opened 2018-02-27 10:54 UTC
If I check for new updates, error always pops up "no internet connection". Obviously, THERE IS normal high-speed internet connection...

**Comment by yehoudin** [comment] 2018-03-03 19:31
In Horos 2.2.0, "Check for updates" will respond that Horos would be up to date, however 2.4.0 was already rolled out....

**Comment by fvpolpeta** [comment] 2018-03-04 23:57
Hi -

Thanks for reporting this. This was caused by a permission issue in our new website. 

It's fixed now. Please, check.

Best Regards

Fauze

**Closed as completed by fvpolpeta** 2018-03-04 23:57 UTC
