### ISSUE TITLE
For Xcode for Sierra

### ISSUE THREAD

**Issue by SriniVest** [horosproject/horos#233] opened 2017-12-12 08:54 UTC
Is the present code or horos build compatible for Xcode 9 / Sierra

**Comment by fvpolpeta** [comment] 2017-12-12 12:23
Hi -

Yes you have two branches:

master: soon giving rise to Horos 3.0
horos_2_0: the current version of Horos

Let me know in case of doubts

Fauze

**Comment by SriniVest** [comment] 2017-12-12 12:28
Okay Thanks for the update
So Horos 3.0 would only work with X Code 9.0 and upwards ie., for Sierra and upwards, am i right
so when can we see this Branch

And horos_2_0 works perfectly fine for which Xcode version

**Comment by SriniVest** [comment] 2017-12-14 06:51
@fvpolpeta I have seen that there is a default Horos branch and Horos_2.0

so which is good for X Code 9.0 { Sierra } is it the default branch

**Comment by fvpolpeta** [comment] 2017-12-14 12:16
Both can be build on Xcode 9.

2_0 is the current source for the 2.x versions.

master will give rise to the 3.x RC versions soon.

Fauze

**Comment by SriniVest** [comment] 2017-12-14 12:22
@fvpolpeta 
Thanks for your reply
At present I have X Code 9.0 beta and Horos does give me fatal error command /sh/bin exited with code 128

why so

**Comment by fvpolpeta** [comment] 2017-12-14 13:57
Please, provide me with some additional details.

You are referring to the building process or Horos execution?

If building, which branch you are trying to build? 2_0 or master?

**Comment by SriniVest** [comment] 2017-12-14 14:19
@fvpolpeta 
here there are 3 branches
one is Default named Horos and I have downloaded this Branch and I have X Code 9.0 beta and I am getting that exception message, when I have build Horos after unzipping the Binaries

**Comment by omrd** [comment] 2017-12-17 05:53
@fvpolpeta I am having the exact same issue. The development branch compiles fine but the default branch (which is better organized) doesn't compile at all. Same error. On High Sierra and XCode 9 release version.

**Comment by aglv** [comment] 2017-12-17 10:17
If you can, clone the horos repository again and compile. It should work. We haven't figured out yet how to fix a previously checked out repository, and the new master uses many submodules for VTK, ITK, GDCM, OpenJPEG, ...

**Comment by fvpolpeta** [comment] 2017-12-17 12:33
Hi there -

The master repository will become official after release of versions 2.4. Meanwhile, branch horos_2_0 is the official build branch.

As you noticed, it’s more organised and maintainable (thanks Alessandro for your efforts).

We are also reformulating Horos documentation to facilitate your work.

In case Alessandro suggestion doesn’t help at all. Try the following:

=> Close XCode

=> Remove Horos source code you checked out previously

=> Install newest XCode version (Don’t use betas, as we don’t use that too)

=> Install brew macos package manager (https://brew.sh/ <https://brew.sh/>)

=> Using command line terminal, use brew to install pkg-config: “brew install pkg-config”

=> Using command line terminal, use brew to install cmake: “brew install cmake”

(pkg-config and cmake are dependencies in the new build system)

=> Do a clean checkout of Horos via command line: git clone <horos git repository uri>

=> Open the Horos project with XCode

=> Go build

Please, let us know your results.

Fauze

**Comment by aglv** [comment] 2017-12-17 12:34
Oh yes Fauze, good thinking, I forgot about the CMake dependency :)

**Comment by fvpolpeta** [comment] 2017-12-17 12:39
Alternatively, it’s possible to download CMake from Kitware directly:

https://cmake.org/ <https://cmake.org/>

This will give them latest version.

But I’m not sure pkg-config will be available anyway.


Second option then:

Download cmake from Kitware

And install pkg-config via brew.


Hope that helps.

Fauze

**Comment by omrd** [comment] 2017-12-17 15:19
Hmm looks like the latest still doesn't work. make is installed already. I think I will have to wait until it becomes the official branch. Any ETA on 3.0?

<img width="277" alt="capture 12-17-17 at 9 18 21 am" src="https://user-images.githubusercontent.com/34616424/34080923-42aab81e-e30b-11e7-8b65-f11327162a71.png">

**Comment by fvpolpeta** [comment] 2017-12-18 03:35
It should work.

I just proceeded with the same outlined instructions and it built successfully. I just made and committed a small change to the project.

Please, checkout from command line in case you are using GitHub desktop app. Do it to a different folder, and try building from there.

In case it still fails, you can expand the building process output to verify in details the failure root cause. Even though XCode is visual, all the building process is carried just like command line calls. All the verbosity is there. 

No ETA yet. 3.0 Release Candidates are planned to appear early next year.

If possible, let us know which kind of work you plan to do with Horos. We are curious about how the software is being used by the community.

Thanks

Fauze

**Comment by omrd** [comment] 2017-12-19 00:33
Hi @fvpolpeta, 

So just to make sure the test is as pure as possible. I went ahead a created a new macOS VM from scratch. It is running High Sierra 10.3.2 and XCode 9.2. I went through the following steps. 

1. Install Homebrew. 
2. Install CMake
3. Clone Horos from Terminal
4. In Xcode -> Unzip binaries.
5. In Xcode -> Build Horos. 

I have tried the exact same process on my main machine as well. I am attaching the errors from Xcode and the log from CMake. This error is produced in both instances similarly. 

[CMake Log.txt](https://github.com/horosproject/horos/files/1569866/CMake.Log.txt)
[Xcode Error.txt](https://github.com/horosproject/horos/files/1569867/Xcode.Error.txt)

**Comment by fvpolpeta** [comment] 2017-12-19 00:44
Hi -

You are missing pkg-config by what I can see.

“”””””” => Using command line terminal, use brew to install pkg-config: “brew install pkg-config” “”””””"

Please, let me know your results.

Fauze

**Comment by omrd** [comment] 2017-12-19 01:16
Success! Thank you for your help Fauze! I wonder if it would be possible to include cmake and pkg-config in the horos source. That way it's a self contained object that can just be built. 

So in case anyone else is interested. 

1. macOS and Xcode install. 
2. Install homebrew
3. Install CMake
4. Install pkg-config
5. Unzip binaries. 
6. Build -> Success. 

As far as what I plan on doing, it's nothing too exciting. I am customizing Xcode to work better in my field (Oral and Maxillofacial Radiology). 

1. ROIs: Get rid of "Length:" label which is pointless. In the area ROIs I will make them display only area. 
2. ROIs: Cycle through ROI colors so that the software automatically sets a new color with each measurement. 
3. Possibly start Swifting some code. 
4. Although too advanced for my level, I would love to one day work on converting the MPR/Curved MPR views to Metal2 and see if there are performance gains.

My field is interesting in that we tend to include a lot of pictures in our reports, and they have to be presentable. It is also unique in that it is very decentralized, so there is no PACS system to connect to. All that stuff is superfluous. I might consider disabling getting rid of it if it'll make Horos run faster.

**Comment by fvpolpeta** [comment] 2017-12-19 01:18
Nice!  Let’s keep in touch. 

We have good plans for 2018 and Horos.

Thanks for your feedback.

Fauze

**Comment by omrd** [comment] 2017-12-19 01:20
I am excited for RC3 (whenever it happens). Horos is near perfect in my opinion. I recommend it to everyone in my field. If it had an airway tool (check out InVivo5) this would probably bring people over. Thanks again for the great work.

**Comment by omrd** [comment] 2017-12-19 04:51
Fauze, sorry to bother again. 

1. I have noticed two things. Cloning from terminal produces a Horos project that's nearly 3GB in size. That's a huge difference compared with just downloading the zip from Github. 

2. Compile time at this point, without changing any code... over 45 minutes. This can't be right. Are you having the same issue?

**Comment by aglv** [comment] 2017-12-19 07:13
* When you clone a repository you obtain a copy of all of its history. This project has 10 years of history and older versions also include big ZIP files for compiled libraries like VTK and ITK. 
* Recently we switched to use submodules for these libraries, and we compile them as part of the process of building Horos. That’s why it takes so long to build. It’s normal. But the libraries are only built once, and re-built if the configuration changes.

**Comment by fvpolpeta** [comment] 2017-12-19 13:06
Closing the issue. This will be consolidated into a Horos Build instructions page.

Thank you all for the contributions. 

Fauze

**Closed as completed by fvpolpeta** 2017-12-19 13:06 UTC
