### ISSUE TITLE
Horos3 MPR and VR delays, slow down, jams,

### ISSUE THREAD

**Issue by mcConti** [horosproject/horos#305] opened 2018-04-02 10:39 UTC
I use two iMac. They are the same hardware.
One -> el Capitan + Osirix v5.8.5 x64
Second -> High Sierra and Horos ..... (3 RC 2)

There is a clear difference in the scrolling images in MPR / c-MPR / VR. Osirix works much "smoother" when rewinding and moving lines in MPR and when rotating VR. Horos has delays and slows down.

I checked several versions of horos (iMac 27, late 2015, 16GB RAM, High Sierra). 
I deleted configuration files every time. 
~ /Documents/Horos Data
~ /Library/Preferences/com.horosproject.horos.plist 
~ /Library/Cookies/com.horosproject.horos.binarycookies
~ /Library/Caches/com.horosproject.horos 
~ /Library/Application Support/Horos

I found that Horos2.3.0Nightly20171112 works noticeably faster / smoother (MPR, VR) than newer versions:
- Horos3.0.0Nightly20180113
- Horos3.0.0Nightly20180209
- Horos3.0.0RC2

Is this only on my iMac? Does anyone else have problems with the smoothness of scroling / rotating MPR and 3D c-MPR and VR?

And a bug H3.0.0.RC2: in VR, 3D presets, table -> when I use preset the mini image of this preset disappears from the table.

**Comment by aglv** [comment] 2018-04-02 19:21
VR preset bug moved to #306, let's focus on your perceived smoothness problems here.

What you notice is possible: VR and MPR are computed through VTK, and up to v2.X we were still using an old version of VTK that was compiled by the OsiriX team years ago. It is possible, that we might not be compiling this component the same way the OsiriX team did. 

I'll look into this. Perhaps, adding compiler optimization will help?

**Comment by fvpolpeta** [comment] 2018-04-02 19:48
Thanks. I would also suggest a module review by using cmake-gui to facilitate the visualization of what we can enable and what we can't or which flags we can add/remove. I guess the cmake config cache is present in branch 2.x. If so, that would facilitate the process.

I believe the other thing that changed - not sure how this could affect - but previous building hosts were Sierra and not High Sierra. Consequently, versions of XCode were possibly different too - maybe something changed in terms of compilation flags too (according to your hypothesis as well). 

I will generate a test build with VTK in Release Mode and ask for test.

Thanks for helping with this.

Fauze

**Comment by aglv** [comment] 2018-04-02 20:30
Curved MPR also wouldn’t be influenced by this, but @mcConti is probably talking about the three mpr views inside the curved mpr viewer. On my side, I didn’t notice any changes in responsiveness.

**Comment by fvpolpeta** [comment] 2018-04-03 01:27
@mcConti 

Let us know if you see any difference.

https://horosproject.org/horos-content/Horos3.0.0RC4_Nightly20180402.dmg

**Comment by mcConti** [comment] 2018-04-03 15:54
Thank you, I will try

*
The three mpr views inside the curved mpr viewer -> yes, that's what I mean

*
I like Horos versions 2.1.1 (best). But I upgrade to High Sierra and there were some problems. 
Next Horos2.3-Nightly20171112 -> I use it till now.
I used 2.2 very short time. I don't remember why. I think that 2.1.1 was better.
With 2.4 there were some problems with stability and in responsiveness.

P.S.
After 2 quite short examinations (~ 500 images in serie) - there is not big difference between version 2.3nb and 3rc4. It is good. But I will try bigger examinations later.
*
A big difference is caused by the change of "LOD". A little to the right (coarse). No visible difference in picture quality but big difference in responsiveness.

*
In 3rc4 VR -> images in miniviewer table (3D presets) -> still the mini-picture disappears after applying the setting.

P.S.2
Question
Example ->  Slices in serie have 1.00 mm thickness. When I change orientation to coronal or sagital, thickness change to 0,326mm. When I come back to axial, thicness change to 0,7mm. Why? If slice is 1mm why interpolate it to 0,3 ... 0,7mm ??

**Comment by aglv** [comment] 2018-04-10 20:19
* Your PS suggests that the problem is resolved with RC4. @fvpolpeta you can probably close this.
* About the VR preset miniviewers, yes there is a bug and I could reproduce it. Please track this problem in #306. This problem has not been fixed yet and I haven't tried to understand what is actually happening, but it seems to me, it has to do with the orientation of the little VRs
* About the reslicing glitch, no idea, I suggest you don't stack it in this issue though.

**Comment by fvpolpeta** [comment] 2018-04-10 21:07
Alright guys. Closing this. 

Assumption here is that VTK being in RELEASE mode did help to minimize Volume operations in 3DMPR.

**Closed as completed by fvpolpeta** 2018-04-10 21:07 UTC
