### ISSUE TITLE
Calibrate angiography, quantify voxels according to their intensity on CT Scans ?

### ISSUE THREAD

**Issue by ArnaudBro** [horosproject/horos#562] opened 2020-04-20 13:37 UTC
Hello,

I am currently using Horos for my end of study project.
I have to take measurements on images of angiographies. When I measure the value given by Horos is in pixels.
My question is as follows: How is it possible to calibrate the image in Horos by knowing either the size of the diagonal of the image or the size of a catheter present on the image?

We are also studying the quantity of calcifications of the aortic valve on CT scans. Is it possible to quantify the volume represented by voxels greater than a certain density in an area, a volume preset on the scanner?

Thank you in advance.
Best regards,

**Comment by jensen0914** [comment] 2020-04-20 19:25
@ArnaudBro This is not a bug or new functionality request, but a request for how to perform some post-processing operations. As you have also requested his help via the Horos Project Google Group, I am closing this as the group is the more appropriate place for help. I will try to address your questions there.

**Closed as completed by jensen0914** 2020-04-20 19:25 UTC
