### ISSUE TITLE
Problem with annotations on MPR

### ISSUE THREAD

**Issue by Antoine341** [horosproject/horos#549] opened 2020-03-11 09:47 UTC
Some annotations are lacking on images in MPR mode, for example  zoom&angle are not displayed in the lower left corner (but they are selected in HOROS preferences).

<img width="1059" alt="Capture d’écran 2020-03-11 à 10 41 03" src="https://user-images.githubusercontent.com/62055663/76403694-916f1d80-6385-11ea-8d9f-12682505aa23.png">
<img width="657" alt="Capture d’écran 2020-03-11 à 10 41 17" src="https://user-images.githubusercontent.com/62055663/76403706-959b3b00-6385-11ea-93fe-864a0cd9175a.png">

**Comment by jensen0914** [comment] 2020-03-11 12:49
This is a duplicate of #535

**Closed as completed** 2020-03-11 12:53 UTC

**Comment by Fu-hh** [comment] 2020-06-09 16:07
I have met the same problem with the last 3 labels missing in every corner. But it worked in April 2020. How to resolve this problem please?😔😔

**Comment by jensen0914** [comment] 2020-06-10 00:03
Hello, Fu-hh, would you please provide the versions of Horos (e.g., 3.3.6, 4.0.0RC4) and macOS you are using? And also which annotations are missing (the ones shown in your preferences but not displaying).
